// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkkxqPxPWh8xRKNd7RlATwq09d0e2BM2k',
    appId: '1:247035356527:web:2d45bc4244c72bcdf9749a',
    messagingSenderId: '247035356527',
    projectId: 'teamist-b7d82',
    authDomain: 'teamist-b7d82.firebaseapp.com',
    storageBucket: 'teamist-b7d82.appspot.com',
    measurementId: 'G-0HSHTC3GJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKCNpUo-x_GmdtBYu8z_3tNkWx8ByaKRk',
    appId: '1:247035356527:android:74be5ca73649629af9749a',
    messagingSenderId: '247035356527',
    projectId: 'teamist-b7d82',
    storageBucket: 'teamist-b7d82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClk9bH6BveXCjDMlExEfvQETUwnZ_Axwc',
    appId: '1:247035356527:ios:1d851f7d23a2155df9749a',
    messagingSenderId: '247035356527',
    projectId: 'teamist-b7d82',
    storageBucket: 'teamist-b7d82.appspot.com',
    iosClientId: '247035356527-6mi5gd09qsl3gb1vi6jvcm9nvvm7mok5.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClk9bH6BveXCjDMlExEfvQETUwnZ_Axwc',
    appId: '1:247035356527:ios:1d851f7d23a2155df9749a',
    messagingSenderId: '247035356527',
    projectId: 'teamist-b7d82',
    storageBucket: 'teamist-b7d82.appspot.com',
    iosClientId: '247035356527-6mi5gd09qsl3gb1vi6jvcm9nvvm7mok5.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamist',
  );
}
